from enum import IntEnum
from typing import Sequence

CHANNEL_POSITION: int
CHANNEL_VITALS: int
CHANNEL_ANIMATION: int
CHANNEL_APPEARANCE: int
CHANNEL_CUSTOM_0: int
MOTION_SAMPLED: int
MOTION_KINETIC: int


class DenseSimError(RuntimeError): ...


class MotionMode(IntEnum):
    SAMPLED: MotionMode
    KINETIC: MotionMode


class DeltaOp(IntEnum):
    UPDATE: DeltaOp
    ENTER: DeltaOp
    LEAVE: DeltaOp
    SPAWN: DeltaOp
    REMOVE: DeltaOp


class DeltaEntry:
    @property
    def entity_id(self) -> int: ...
    @property
    def channel_mask(self) -> int: ...
    @property
    def operation(self) -> int: ...
    @property
    def operation_name(self) -> str: ...


class ChunkDeltaView:
    @property
    def chunk_x(self) -> int: ...
    @property
    def chunk_y(self) -> int: ...
    @property
    def entry_count(self) -> int: ...
    @property
    def subscriber_count(self) -> int: ...
    @property
    def entries(self) -> Sequence[DeltaEntry]: ...
    @property
    def subscribers(self) -> Sequence[int]: ...


class FanoutView(Sequence[ChunkDeltaView]):
    @property
    def tick(self) -> int: ...
    @property
    def chunk_count(self) -> int: ...
    @property
    def delta_count(self) -> int: ...
    @property
    def subscriber_count(self) -> int: ...
    @property
    def groups(self) -> Sequence[ChunkDeltaView]: ...


class World:
    def __init__(
        self,
        cell_size: int = 8,
        chunk_size: int = 16,
        initial_entity_capacity: int = 1024,
        initial_observer_capacity: int = 64,
    ) -> None: ...
    def close(self) -> None: ...
    def begin_tick(self, tick: int, /) -> None: ...
    def end_tick(self) -> None: ...
    def fanout_view(self) -> FanoutView: ...
    def spawn(self, entity_id: int, spatial_x: int, spatial_y: int, type_mask: int, /) -> None: ...
    def move(self, entity_id: int, spatial_x: int, spatial_y: int, /) -> None: ...
    def move_many(self, entity_ids: object, xs: object, ys: object, /) -> int: ...
    def set_motion_plan(self, entity_id: int, start_tick: int, until_tick: int, x: float, y: float, vx: float, vy: float, /) -> None: ...
    def clear_motion_plan(self, entity_id: int, /) -> None: ...
    def motion_mode(self, entity_id: int, /) -> int: ...
    def remove(self, entity_id: int, /) -> None: ...
    def mark_dirty(self, entity_id: int, channel_mask: int, /) -> None: ...
    def mark_dirty_many(self, entity_ids: object, channel_masks: object | int, /) -> int: ...
    def entity_exists(self, entity_id: int, /) -> bool: ...
    def entity(self, entity_id: int, /) -> dict[str, int]: ...
    def create_observer(self, radius: int, type_mask: int, /) -> int: ...
    def destroy_observer(self, observer_id: int, /) -> None: ...
    def anchor_observer(self, observer_id: int, entity_id: int, /) -> None: ...
    def set_observer_position(self, observer_id: int, spatial_x: int, spatial_y: int, /) -> None: ...
    def set_observer_radius(self, observer_id: int, radius: int, /) -> None: ...
    def observer_exists(self, observer_id: int, /) -> bool: ...
    def observer(self, observer_id: int, /) -> dict[str, int | bool]: ...
    @property
    def tick_is_open(self) -> bool: ...
    @property
    def current_tick(self) -> int: ...
    @property
    def entity_count(self) -> int: ...
    @property
    def entity_capacity(self) -> int: ...
    @property
    def observer_count(self) -> int: ...
    @property
    def motion_metrics(self) -> dict[str, int]: ...
